<?php

/**
 * @file
 * Enables wipe of search index.
 */

/**
 * Implements hook_menu().
 */
function searchindex_wipe_menu() {
  // Confirmation form to wipe search index.
  $items['admin/searchindex_wipe'] = array(
    'title' => 'Clear Index',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('searchindex_wipe_confirm'),
    'access arguments' => array('wipe search index'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function searchindex_wipe_permission() {
  return array(
    'wipe search index' => array(
      'title' => t('Wipe Search Index'),
      'description' => t('Permission to wipe search index.'),
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function searchindex_wipe_form_search_admin_settings_alter(&$form, &$form_state) {
  if (user_access('wipe search index')) {
    if ($form['indexing']['wipe']) {
      $invalidate = $form['indexing']['wipe'];
      unset($form['indexing']['wipe']);
      $status = $form['indexing']['status'];
      unset($form['indexing']['status']);
      $description = $form['indexing']['#description'];
      unset($form['indexing']['#description']);
      $form['status'] = array(
        '#type' => 'fieldset',
        '#title' => 'Indexing status',
        'status' => $status,
        '#description' => $description,
        'invalidate' => $invalidate,
        'wipe' => array(
          '#value' => t('Wipe Index'),
          '#type' => 'submit',
          '#submit' => array('searchindex_wipe_all'),
          '#description' => t('Drops all the index build by search module'),
        ),
      );
    }
  }
}

/**
 * Redirect to confirmation link.
 */
function searchindex_wipe_all(&$form, &$form_state) {
  $form_state['redirect'] = array('admin/searchindex_wipe');
}

/**
 * Implements hook_help().
 */
function searchindex_wipe_help($path, $arg) {
  switch ($path) {
    // Main module help for the block module.
    case 'admin/config/search/settings':
      return '<p>' . t('Enables clearing of Search related indexes, so that search related tables do not grow large. To Re-index the site, You first need to click on Wipe Index button.') . '</p>';
  }
}

/**
 * Confirmation form.
 */
function searchindex_wipe_confirm($form, $form_state) {
  $form['status'] = array(
    '#prefix' => '<p>',
    '#suffix' => '</p>',
    '#markup' => t('This will effectively drop all the search index built so far by Search module.'),
  );
  return confirm_form($form, t('Are you sure you want to clear Search index?'), "admin/config/search/settings", t('This action cannot be undone.'), t('Delete'), t('Cancel')
  );
}

/**
 * Confirmation form submit. Truncates all search related tables.
 */
function searchindex_wipe_confirm_submit($form, &$form_state) {
  if ($form_state['values']['confirm']) {
    searchindex_wipe_truncate_table();
  }
  $form_state['redirect'] = 'admin/config/search/settings';
}

/**
 * Trancate the search index table.
 */
function searchindex_wipe_truncate_table() {
  // Taken code from backdrop_uninstall_schema.
  $schema = backdrop_get_schema_unprocessed('search');
  foreach ($schema as $table_name => $table) {
    // Truncate search related tables.
    db_truncate($table_name)->execute();
  }
  backdrop_set_message(t('Search Index cleared. Please rebuilt the index by running cron.'));
}
